# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./TruckBooking
    
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAVAP3QSUCQYB72GMB'
        aws-secret-access-key: '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'
        aws-region: 'ap-south-1'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      
    - run: cd ~/actions-runner/deploy/loadsApi/loadsApi/TruckBooking
    - run: sudo docker container stop load-container || true
    - run: sudo docker container stop loadPostgres || true
    - run: sudo docker container rm load-container || true
    - run: sudo docker image rm load || true
    - run: sudo docker build -t load .
    - run: sudo docker container start loadPostgres || sudo docker run --name loadPostgres -e POSTGRES_ROOT_PASSWORD=postgres -e POSTGRES_DATABASE=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:alpine
    - run: sudo docker run --env-file /home/ubuntu/test.env -p 8080:8080 --name load-container --link loadPostgres:postgres load | echo "success" 

 
